### PR TITLE
Update "getting started" docs link

### LINKED ISSUE #73: Docs link "getting started" is 404
Looks like https://charmhub.io/jenkins-k8s/docs/getting-started should be replaced with https://charmhub.io/jenkins-k8s/docs/tutorial-getting-started

### PR DESCRIPTION
**Pull request by jsimpso**
Fixes #73

### Overview

Fix documentation link.

### Rationale

Existing link is oudtdated and 404's.

### Juju Events Changes

N/A

### Module Changes

N/A

### Library Changes

N/A

### Checklist

- [ ] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied
- [ ] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [ ] The changes are compliant with [ISD054 - Managing Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [ ] The documentation is generated using `src-docs`
- [ ] The documentation for charmhub is updated.
- [ ] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)

Largely N/A, single trivial documentation link update.

### CODE REVIEW

**Review by jdkandersson — APPROVED** [review]

**Review by arturo-seijas — APPROVED** [review]
Thanks!

**Comment by yanksyoon** [comment]
/canonical/self-hosted-runners/run-workflows 419389a70dad0ac4d11bca1aa6d88fe248857521

**Review by gregory-schiano — APPROVED** [review]
LGTM

**Review by jdkandersson — APPROVED** [review]

**Comment by yanksyoon** [comment]
/canonical/self-hosted-runners/run-workflows cb64b1c78cdb5a2a49b1c4d80191eca9484fbcf1

**Comment by yanksyoon** [comment]
/canonical/self-hosted-runners/run-workflows bce140186296511807e8af494d17bc62e874b258

**Comment by yanksyoon** [comment]
/canonical/self-hosted-runners/run-workflows a01860d26cf267db656ae5c3df5689cc105123ae

**Comment by jdkandersson** [comment]
@yanksyoon I retriggered the tests, not sure if this should be passing now?

**Comment by jdkandersson** [comment]
/canonical/self-hosted-runners/run-workflows 01bd5a81bb5ee2cc6c17039b278f500e3a8207e8

**Comment by jdkandersson** [comment]
I think we saw the issue of not being able to upload rocks to ghcr.io on other PRs from forks - I don't think there is much we can do. Since it is a change to the readme I'll merge without the checks passing

**Pull request merged**
