### PR TITLE
jenkins-k8s: ingress support

### PR DESCRIPTION
**Pull request by Thanhphan1147**
Applicable spec: <link>

### Checklist

- [ ] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied
- [ ] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [ ] The changes are compliant with [ISD054 - Managing Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [ ] The documentation is generated using `src-docs`
- [ ] The documentation for charmhub is updated.
- [ ] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)

### CODE REVIEW

**Review by yanksyoon — COMMENTED** [review]
image
There is an option under /manage/configure, Jenkins Location > Jenkins URL which Jenkins uses to refer to itself. Would you be able to add that to the change as well please?
I think you might have forgotten to check the checklists too :D

**Comment by Thanhphan1147** [comment]
> image There is an option under /manage/configure, Jenkins Location > Jenkins URL which Jenkins uses to refer to itself, which I think would be required for this to work :)

Nice, thanks for the tip.

**Comment by Thanhphan1147** [comment]
Ingress seems to be working fine even without the jenkins config on my local environment, which confuses me. Do you have an example of when this might now work without the config? @yanksyoon

**Comment by yanksyoon** [comment]
@Thanhphan1147 I think this might not work when there might be redirects outside of the local environment? Don't have a specific case though. Do redirects happen to the correct ingress address?

**Comment by amandahla** [comment]
Is this PR ready for review? There is no description/checkboxes.

**Comment by arturo-seijas** [comment]
I'm closing this, provided we've merged https://github.com/canonical/jenkins-k8s-operator/pull/58

**Pull request closed without merging**
